In [23]:
import pandas as pd
import numpy as np

## Worklist prioritization: Emergency Setting

In [49]:
## First, read in the file of the current worklist with the probabilities that your two algorithms have
## generated for the two types of findings you're most concerned with:

worklist = pd.read_csv('probabilities.csv')

In [50]:
init_TAT = []
max_prob = []
for i, r in worklist.iterrows():
    init_TAT.append((i+1)*6)
    max_prob.append(np.max([r['Brain_bleed_probability'], r['Aortic_dissection_probability']]))
    
worklist['init_TAT'] =   init_TAT
worklist['max_prob'] =   max_prob

worklist

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,init_TAT,max_prob
0,chest_xray,0.00,0.05,6,0.05
1,chest_xray,0.00,0.17,12,0.17
2,chest_xray,0.00,0.00,18,0.00
3,chest_xray,0.00,0.04,24,0.04
4,wrist_xray,0.00,0.00,30,0.00
...,...,...,...,...,...
94,chest_xray,0.00,0.06,570,0.06
95,head_ct,0.90,0.00,576,0.90
96,head_ct,0.45,0.00,582,0.45
97,femur_xray,0.00,0.00,588,0.00
98,chest_xray,0.00,0.00,594,0.00

In [41]:
worklist.Image_Type.unique().tolist()

['chest_xray', 'wrist_xray', 'femur_xray', 'head_ct']

In [52]:
new_worklist = worklist.copy(deep=True)


# new_worklist =  new_worklist.sort_values(['Brain_bleed_probability', 'Aortic_dissection_probability'], ascending=False).reset_index(drop=True)
new_worklist =  new_worklist.sort_values(['max_prob'], ascending=False).reset_index(drop=True)


new_TAT = []
for i, r in new_worklist.iterrows():
    new_TAT.append((i+1)*6)    
new_worklist['new_TAT'] =   new_TAT


diff_TAT = []
for i, r in new_worklist.iterrows():
    diff_TAT.append(r['init_TAT']-r['new_TAT'])
new_worklist['diff_TAT'] =   diff_TAT



new_worklist

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,init_TAT,max_prob,new_TAT,diff_TAT
0,head_ct,0.99,0.00,156,0.99,6,150
1,chest_xray,0.00,0.95,96,0.95,12,84
2,chest_xray,0.00,0.94,66,0.94,18,48
3,chest_xray,0.00,0.93,456,0.93,24,432
4,chest_xray,0.00,0.93,288,0.93,30,258
...,...,...,...,...,...,...,...
94,femur_xray,0.00,0.00,444,0.00,570,-126
95,chest_xray,0.00,0.00,228,0.00,576,-348
96,wrist_xray,0.00,0.00,216,0.00,582,-366
97,wrist_xray,0.00,0.00,204,0.00,588,-384
98,chest_xray,0.00,0.00,594,0.00,594,0

### If your algorithm's goal was to have brain bleeds read 30 minutes faster, how did it do?

In [54]:
goal1 = new_worklist[(new_worklist.diff_TAT > 30) & (new_worklist.Image_Type == 'head_ct') ]
print (len(goal1))
goal1

14

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,init_TAT,max_prob,new_TAT,diff_TAT
0,head_ct,0.99,0.0,156,0.99,6,150
5,head_ct,0.91,0.0,510,0.91,36,474
6,head_ct,0.90,0.0,576,0.90,42,534
7,head_ct,0.89,0.0,258,0.89,48,210
8,head_ct,0.89,0.0,360,0.89,54,306
15,head_ct,0.78,0.0,540,0.78,96,444
16,head_ct,0.77,0.0,240,0.77,102,138
17,head_ct,0.75,0.0,276,0.75,108,168
23,head_ct,0.69,0.0,462,0.69,144,318
32,head_ct,0.45,0.0,582,0.45,198,384
33,head_ct,0.44,0.0,474,0.44,204,270
42,head_ct,0.22,0.0,342,0.22,258,84
53,head_ct,0.07,0.0,414,0.07,324,90
55,head_ct,0.05,0.0,498,0.05,336,162

### If your algorithm's goal was to have aortic dissections read 15 minutes faster, how did it do?

In [56]:
goal2 = new_worklist[(new_worklist.diff_TAT >= 15) & (new_worklist.Image_Type == 'chest_xray') ]
print (len(goal2))
goal2

28

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,init_TAT,max_prob,new_TAT,diff_TAT
1,chest_xray,0.0,0.95,96,0.95,12,84
2,chest_xray,0.0,0.94,66,0.94,18,48
3,chest_xray,0.0,0.93,456,0.93,24,432
4,chest_xray,0.0,0.93,288,0.93,30,258
9,chest_xray,0.0,0.84,294,0.84,60,234
10,chest_xray,0.0,0.83,234,0.83,66,168
11,chest_xray,0.0,0.82,378,0.82,72,306
12,chest_xray,0.0,0.82,528,0.82,78,450
13,chest_xray,0.0,0.81,270,0.81,84,186
14,chest_xray,0.0,0.79,516,0.79,90,426
18,chest_xray,0.0,0.73,492,0.73,114,378
19,chest_xray,0.0,0.72,324,0.72,120,204
20,chest_xray,0.0,0.71,168,0.71,126,42
21,chest_xray,0.0,0.71,312,0.71,132,180
22,chest_xray,0.0,0.70,402,0.70,138,264
27,chest_xray,0.0,0.60,282,0.60,168,114
28,chest_xray,0.0,0.60,420,0.60,174,246
30,chest_xray,0.0,0.49,564,0.49,186,378
31,chest_xray,0.0,0.48,426,0.48,192,234
34,chest_xray,0.0,0.38,438,0.38,210,228
38,chest_xray,0.0,0.26,558,0.26,234,324
39,chest_xray,0.0,0.26,372,0.26,240,132
47,chest_xray,0.0,0.15,450,0.15,288,162
48,chest_xray,0.0,0.15,546,0.15,294,252
50,chest_xray,0.0,0.11,480,0.11,306,174
51,chest_xray,0.0,0.11,504,0.11,312,192
54,chest_xray,0.0,0.06,570,0.06,330,240
57,chest_xray,0.0,0.04,468,0.04,348,120

### Were there any cases where your algorithm made it worse for patients who needed an ASAP read? Could anything have been done about this?

In [57]:
goal3 = new_worklist[(new_worklist.diff_TAT < 0) &  (new_worklist.max_prob > 0.5)]
print (len(goal3))
goal3

2

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,init_TAT,max_prob,new_TAT,diff_TAT
24,chest_xray,0.00,0.67,36,0.67,150,-114
25,head_ct,0.67,0.00,114,0.67,156,-42